In [2]:
import numpy as np
from numpy.linalg import linalg
a = np.array([[1, -2, 3],[4, -5 ,7]])
b = np.array([[1, 2],[1, 1], [2,0]])

print(np.matmul(a, b).transpose())
print(a.transpose())
print(b.transpose())

print(np.matmul(a.transpose(), b.transpose()).transpose())

[[ 5 13]
 [ 0  3]]
[[ 1  4]
 [-2 -5]
 [ 3  7]]
[[1 1 2]
 [2 1 0]]
[[  9 -12  17]
 [  5  -7  10]
 [  2  -4   6]]


In [3]:
a = np.array([[2, 1],[-1 ,0]])

print(linalg.inv(a))

[[ 0. -1.]
 [ 1.  2.]]


In [6]:
a = np.array([[2, 1],[-1 ,0]])

a.transpose()
print(linalg.inv(a.transpose()))

[[ 0.  1.]
 [-1.  2.]]


In [7]:
print(linalg.inv(a).transpose())



[[ 0.  1.]
 [-1.  2.]]
