In [1]:
import numpy as np

a = np.array([[2,0],[1,0]]) 
b = np.array([[0,0],[3,1]])
print("AB","=",a.dot(b))
print("")

AB = [[0 0]
 [0 0]]



In [2]:
a = np.array([[1,1],[-1,1]]) 
b = np.array([[0.5,-0.5],[0.5,0.5]])
print(a.dot(b))
print(b.dot(a))


[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [3]:
a = np.array([[1,-2,3],[4,-5,7]]) 
b = np.array([[1,2],[1,1],[2,0]])
print(a.dot(b))
print(b.dot(a))

[[ 5  0]
 [13  3]]
[[  9 -12  17]
 [  5  -7  10]
 [  2  -4   6]]


In [4]:
a = np.array([[1,-2,3],[4,-5,7]]) 
b = np.array([[1,2],[1,1],[2,0]])
a_trans = a.T
b_trans = b.T
print(a.dot(b).T)
print(a_trans)
print(b_trans)
print(b_trans.dot(a_trans))


[[ 5 13]
 [ 0  3]]
[[ 1  4]
 [-2 -5]
 [ 3  7]]
[[1 1 2]
 [2 1 0]]
[[ 5 13]
 [ 0  3]]


In [5]:
a = np.array([[2,1],[-1,0]])
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0. -1.]
 [ 1.  2.]]


In [6]:
a = np.array([[2,1],[-1,0]])
a_inv = np.linalg.inv(a)
a_trans = a.T
a_trans_inv = np.linalg.inv(a_trans)
a_inv_trans = a_inv.T
print(a_trans)
print(a_trans_inv)
print(a_inv_trans) 

[[ 2 -1]
 [ 1  0]]
[[ 0.  1.]
 [-1.  2.]]
[[ 0.  1.]
 [-1.  2.]]


In [7]:
a = np.array([["a11","a12","...","a1n"],["a21","a22","...","a2n"],["...","...","...","..."],["an1","an2","...","ann"]])
print("A","=",a)
x = np.array([["x1"],["x2"],["..."],["xn"]])
print("x","=",x)
b = np.array([["b1"],["b2"],["..."],["bn"]])
print("b","=",b)

A = [['a11' 'a12' '...' 'a1n']
 ['a21' 'a22' '...' 'a2n']
 ['...' '...' '...' '...']
 ['an1' 'an2' '...' 'ann']]
x = [['x1']
 ['x2']
 ['...']
 ['xn']]
b = [['b1']
 ['b2']
 ['...']
 ['bn']]


In [8]:
import pandas as pd

allroutes = pd.read_excel("routes.xlsx",sheet_name = "Sheet1",engine = "openpyxl")
demand_delivery = pd.read_excel("data-demands-deliveyconstraint.xlsx",sheet_name = "Sheet1",engine = "openpyxl")
demand_stop1 = demand_delivery.copy()
demand_stop1.columns = ["Stores_1","Demands_Stop 1","Delivery Contraints_Stop 1"]
demand_stop2 = demand_delivery.copy()
demand_stop2.columns = ["Stores_2","Demands_Stop 2","Delivery Contraints_Stop 2"]
combined_data = pd.merge(allroutes,demand_stop1, how="left", left_on = "stop1", right_on = "Stores_1")
data = pd.merge(combined_data,demand_stop2, how="left", left_on = "stop2", right_on = "Stores_2")
data = data.drop(columns=['Stores_1', 'Stores_2'])
data

Route# stop1 stop2  Demands_Stop 1  Delivery Contraints_Stop 1  \
0        1    S1   NaN             194                          64   
1        2    S2   NaN             201                          50   
2        3    S3   NaN             169                          28   
3        4    S4   NaN             228                          57   
4        5    S5   NaN             237                          47   
5        6    S6   NaN             190                          63   
6        7    S7   NaN             166                          26   
7        8    S8   NaN             158                          31   
8        9    S9   NaN             209                          69   
9       10   S10   NaN             219                          43   
10      11   S11   NaN             178                          59   
11      12   S12   NaN             154                          30   
12      13   S13   NaN             161                          24   
13      14   S14   NaN             157                          39   
14      15   S15   NaN             247                          61   
15      16   S16   NaN             217                          54   
16      17   S17   NaN             212                          34   
17      18   S18   NaN             161                          31   
18      19   S19   NaN             158                          31   
19      20   S20   NaN             194                          32   
20      21    S5    S7             237                          47   
21      22    S8   S10             158                          31   
22      23    S3   S11             169                          28   
23      24    S6   S12             190                          63   
24      25    S4   S13             228                          57   
25      26   S18   S14             161                          31   
26      27   S11    S7             178                          59   
27      28   S12    S8             154                          30   
28      29   S13    S9             161                          24   
29      30   S17   S10             212                          34   

    Demands_Stop 2  Delivery Contraints_Stop 2  
0              NaN                         NaN  
1              NaN                         NaN  
2              NaN                         NaN  
3              NaN                         NaN  
4              NaN                         NaN  
5              NaN                         NaN  
6              NaN                         NaN  
7              NaN                         NaN  
8              NaN                         NaN  
9              NaN                         NaN  
10             NaN                         NaN  
11             NaN                         NaN  
12             NaN                         NaN  
13             NaN                         NaN  
14             NaN                         NaN  
15             NaN                         NaN  
16             NaN                         NaN  
17             NaN                         NaN  
18             NaN                         NaN  
19             NaN                         NaN  
20           166.0                        26.0  
21           219.0                        43.0  
22           178.0                        59.0  
23           154.0                        30.0  
24           161.0                        24.0  
25           157.0                        39.0  
26           166.0                        26.0  
27           158.0                        31.0  
28           209.0                        69.0  
29           219.0                        43.0

In [9]:
def route_stop(route,stop):
    if str(stop) == "nan":
        return None
    else:
        return "R"+str(route)+"_"+str(stop)+"_"
data["Route_Stop 1"] = data.apply(lambda x: route_stop(x['Route#'], x['stop1']), axis=1)
data["Route_Stop 2"] = data.apply(lambda x: route_stop(x['Route#'], x['stop2']), axis=1)
routevariables = list(data["Route_Stop 1"])
routevariables = routevariables + list(data["Route_Stop 2"].dropna())
counter_day = 1
variables = []

while counter_day <= 7:
    route_counter = 1
    while route_counter <= len(routevariables):
        x = "D_Day" + str(counter_day)
        x = x +"_"+routevariables[route_counter-1]
        variables.append(x)
        route_counter = route_counter + 1
    counter_day = counter_day + 1

In [13]:
stores = list(demand_delivery["Stores"])
days = ["Day1","Day2","Day3","Day4","Day5","Day6","Day7"]
routes = list(allroutes["Route#"])

import gurobipy as grb

#Setting Model
model = grb.Model('Transportation')

#Setting Variables

counter = 1
while counter <= len(variables):
    vars()[variables[counter-1]] = model.addVar(name = variables[counter-1])
    counter = counter + 1

# Setting Objective
obj_var = []
for x in range(len(variables)):
    obj_var.append(vars()[variables[x]])
model.setObjective(sum(obj_var), sense = grb.GRB.MINIMIZE)

# Setting Shop Week Demand Constraint
for x in stores:
    store_var = [k for k in variables if (x+"_") in k]
    store_demand = float(demand_delivery[demand_delivery["Stores"]== x ]["Demands (per week)"])
    con_var = []
    for y in range(len(store_var)):
        con_var.append(vars()[store_var[y]])
    model.addConstr(sum(con_var) >= store_demand, name = ("Demand of "+x))

# Setting Shop Delivery Accepting Constraint
for d in days:
    for s in stores:
        store_var = [k for k in variables if ((s+"_") in k )and(d in k)]
        store_accept = float(demand_delivery[demand_delivery["Stores"]== s ]["Delivery accepting constraints"])
        con_var = []
        for y in range(len(store_var)):
             con_var.append(vars()[store_var[y]])
        model.addConstr(sum(con_var) <= store_accept, name = ("Accept Demand of "+s+" on "+d))
        
# Setting Truck Constraint
for d in days:
    for r in routes:
        route_var = [k for k in variables if (("R"+str(r)+"_") in k )and(d in k)]
        con_var = []
        for y in range(len(route_var)):
             con_var.append(vars()[route_var[y]])
        model.addConstr(sum(con_var) <= 50.0, name = ("Truck capacity of route "+str(r)+" on "+d))

# Non-negative Constraint
for x in variables:
    model.addConstr(vars()[x] >= 0.0, name = ("Non-negative constraint of "+x))

    
#Optimising Step
model.optimize()


print("-------------------------------------")
solution_name = []
solution_value = []

# Print Optimal Solution
for v in model.getVars():
    print('%s = %d'%(v.varName, v.x))
    solution_name.append(v.varName)
    solution_value.append(v.x)

print("-------------------------------------")
    
# Print Optimal Value
print('Objective value: %g' % model.objVal)


Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 650 rows, 280 columns and 1120 nonzeros
Model fingerprint: 0xed8ab024
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+01, 2e+02]
Presolve removed 468 rows and 42 columns
Presolve time: 0.02s
Presolved: 182 rows, 238 columns, 616 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.2110000e+03   6.497500e+02   0.000000e+00      0s
     133    3.8100000e+03   0.000000e+00   0.000000e+00      0s

Solved in 133 iterations and 0.03 seconds
Optimal objective  3.810000000e+03
-------------------------------------
D_Day1_R1_S1_ = 50
D_Day1_R2_S2_ = 0
D_Day1_R3_S3_ = 0
D_Day1_R4_S4_ = 50
D_Day1_R5_S5_ = 23
D_Day1_R6_S6_ = 50
D_Day1_R7_S7_ = 0
D_Day1_R8_S8_ = 0
D_Day1_R9_S9_ = 50
D_Day1_R10_S10_ = 0
D_Day1_R11_S

In [36]:
solution_df = pd.DataFrame(list(zip(solution_name,solution_value)),columns = ["Variable","Value"])
solution_df = solution_df[solution_df["Value"] != 0]
solution_df[["Day","Route","Shop"]] = solution_df["Variable"].str.split('_', expand=True)[[1,2,3]]
solution_df = solution_df[["Day","Route","Shop","Value"]]
solution_df

Day Route Shop  Value
0    Day1    R1   S1   50.0
3    Day1    R4   S4   50.0
4    Day1    R5   S5   23.0
5    Day1    R6   S6   50.0
8    Day1    R9   S9   50.0
..    ...   ...  ...    ...
255  Day7   R16  S16   50.0
256  Day7   R17  S17   34.0
257  Day7   R18  S18   31.0
258  Day7   R19  S19   31.0
259  Day7   R20  S20    2.0

[119 rows x 4 columns]

In [37]:
solution_df.to_excel("Solutions.xlsx") 