In [1]:
from gurobipy import *
from math import sqrt
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import xlrd

In [18]:
m = Model('SuDoKu')
# Load data
initgrid = np.zeros([9,9])

# Solve model
x = m.addVars(9,9,9,vtype = GRB.BINARY)

m.addConstrs(quicksum(x[i,j,k] for j in range(9)) == 1 for i in range(9) for k in range(9))
m.addConstrs(quicksum(x[i,j,k] for i in range(9)) == 1 for j in range(9) for k in range(9))
m.addConstrs(quicksum(x[r,c,k] for r in np.arange(3*i,3*i+3) for c in np.arange(3*j, 3*j+3)) == 1 
            for i in range(3) for j in range(3) for k in range(9))
m.addConstrs(quicksum(x[i,j,k] for k in range(9)) == 1 for i in range(9) for j in range(9))

m.setObjective( 0*x[0,0,0] , GRB.MINIMIZE)
m.optimize()


# Check solution
p = m.getAttr('x', x)
for i in range(9):
    for j in range(9):
        for k in range(9):
            if p[i,j,k] == 1:
                #print('%g, %g is %g' %(i,j,k))
                initgrid[i,j] = k+1
print(initgrid)

Optimize a model with 324 rows, 729 columns and 2916 nonzeros
Variable types: 0 continuous, 729 integer (729 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.0000000

Explored 0 nodes (0 simplex iterations) in 0.05 seconds
Thread count was 1 (of 4 available processors)

Solution count 1: 0 

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%
[[3. 4. 5. 6. 2. 8. 7. 1. 9.]
 [7. 6. 8. 1. 9. 3. 4. 5. 2.]
 [2. 9. 1. 5. 4. 7. 3. 6. 8.]
 [4. 1. 6. 3. 5. 9. 8. 2. 7.]
 [5. 7. 9. 4. 8. 2. 6. 3. 1.]
 [8. 2. 3. 7. 1. 6. 5. 9. 4.]
 [9. 3. 2. 8. 6. 4. 1. 7. 5.]
 [1. 8. 7. 9. 3. 5. 2. 4. 6.]
 [6. 5. 4. 2. 7. 1. 9. 8. 3.]]
